AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Me guie de las siguientes fuentes oficiales:

  walktrhough
  https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/working-with-templates-cfn-designer-walkthrough-createbasicwebserver.html

  reference cloudformation EC2
  https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-instance.html

  ejemplo
  https://docs.aws.amazon.com/es_es/AWSCloudFormation/latest/UserGuide/quickref-ec2.html


Resources:
  WebServerSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Allow access from HTTP and SSH traffic
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '80'
          ToPort: '80'
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: '8000'
          ToPort: '8000'
          CidrIp: 0.0.0.0/0
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 2e76192b-a4f8-48a5-92b6-abbfa8b83263
  WebServerInstance:
    Type: 'AWS::EC2::Instance'
    Properties:
      Tags:
        - Key: "Name"
          Value: "josue-server"
      InstanceType: t2.medium
      ImageId: ami-08c40ec9ead489470
      KeyName: !Ref NewKeyPair
      SecurityGroups:
        - !Ref WebServerSecurityGroup

Parameters:
  NewKeyPair:
    Type: String
    Default: tu-key-pair-name #sin la extension